### ISSUE TITLE
Dynamic Transport Error : There was an error processing this Transport Component

### ISSUE THREAD

**Issue by th0m4s** [SlimeVoid/DynamicTransport#43]
Hello,
I've just installed Dynamic Transport on my server, but when I right-click on the Elevator Computer, this error comes : There was an error processing this Transport Component at ...

What is this error ?
Thank you in advance.

Sorry for any mistakes, I'm french !

**Comment by Tarig0** [comment]
What version?

**Comment by th0m4s** [comment]
It's in MC 1.7.10 with forge 10.4.1448 with DynamicTransport v1.2.0 (according to the file name)

**Comment by Tarig0** [comment]
Closing due to rewrite for 1.15
