### ISSUE TITLE
Elevator platform stuck in endless loop.

### ISSUE THREAD

**Issue by VoidAdept** [SlimeVoid/DynamicTransport#46]
**Version:** Dynamic Transport 1.7.x and SlimevoidLibrary-2.0.4.7, on Minecraft 1.7.10 with Forge Modloader 10.13.4.1614-universal. ~60 other mods installed.

**Singleplayer World.**

Elevator entity became stuck in a endless loop after a unrelated crash. Upon reloading the platform was looping downwards for around 20 blocks, then teleporting back to the top and repeating. Can however be blocked by placing blocks below it. It still functions as a physical object (very bouncy if stood upon) and cannot be removed either by creative hand, WorldEdit or /kill command. 

Removing all linked elevator blocks as well has no effect on its indestructability. Could only be removed by uninstalling the mod, reloading the save, then exit and reinstalling.

Calling the same elevator causes a new platform, without the applied camo textures, to spawn and function as normal. The new elevator phases through it like it did not exist.

**Comment by TomberWolf** [comment]
+1

**Comment by hammer354** [comment]
Fixed in my fork, you can download it from https://github.com/hammer354/DynamicTransport/releases

**Comment by Tarig0** [comment]
Closing due to rewrite for 1.15
