### ISSUE TITLE
Re-implement Destination marker GUI

### ISSUE THREAD

**Issue by SolDev69** [SlimeVoid/DynamicTransport#49]
Latest forge and DynamicTransport 1.15 version. The destination marker is hooked up to the controller but nothing happens when I right click.

**Comment by Tarig0** [comment]
Working as currently intended. Will be working on GUI elements once forge pulls in my multipart entity changes.

for now you must use redstone signal to interact with the markers

**Comment by Tarig0** [comment]
1.12.2 has this implemented will be porting to 1.15 - 1.16 soon
