### ISSUE TITLE
Elevator Block (Entity) is stuck and impossible to remove

### ISSUE THREAD

**Issue by SoldatJess** [SlimeVoid/DynamicTransport#51]
I'm playing on a Aternos server with a friend. The server first crashed and when we joined back after re launching it, the elevator was glitched. Two of the elevator blocks were stuck as entities on the ground and it was impossible to taked them off. What should i do ?
![ElevatorBug](https://user-images.githubusercontent.com/69813412/90424930-38877c00-e0bf-11ea-9f99-6af6cc8e5971.PNG)

**Comment by Tarig0** [comment]
what version of the mod are you on? I thought the newer stuff would not have this issue  anymore

**Comment by SoldatJess** [comment]
I'm in 1.7.10 so no /kill @e

**Comment by Tarig0** [comment]
This might add a kill command

https://www.curseforge.com/minecraft/mc-mods/cofh-core/files/2388750

**Comment by SoldatJess** [comment]
It woked, thanks !
