### ISSUE TITLE
No Maintenance Mode On Controller

### ISSUE THREAD

**Issue by DDX5-DX12-Chip** [SlimeVoid/DynamicTransport#52]
Forge Version: 14.23.5.2847
Mod Version:  1.0.2-alpha
Java Version: jdk 1.8_251
OS: Windows 7 Pro 64 bit
Ram: 20GB allocated of 24GB

Has This Feature Been Removed Or Is This A Bug.

**Comment by Tarig0** [comment]
The maintenance mode is no longer required. The controller keeps track of the elevator and can be modified when ever the elevator is stopped.
